### ISSUE TITLE
Shotgrid session collection doesn't get user correctly

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-shotgrid#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Issue reported in https://discord.com/channels/517362899170230292/563751989075378201/1266079526283116655

When publishing to Flow/SG, I noticed that it publishes as "ayon_user_publishing 1.0" and not the user, and it seems to only be publishing a still frame not the video file the farm generated.

### Expected Behavior:

shot grid should get the correct user name

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. change login type
2. publish a review from any host

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by kalisp** [comment]
Should https://github.com/ynput/ayon-shotgrid/pull/118 be fixing this?

**Comment by kalisp** [comment]
Couldnt reproduce, linked PR wouldnt work in Nuke and potentially other DCCs
