### ISSUE TITLE
Feature Request: Synchronising SG Fields to AYON

### ISSUE THREAD

**Issue by matteoveglia** [ynput/ayon-shotgrid#55]
Breaking this issue out from a larger thread.
_Originally posted by @matteoveglia in https://github.com/ynput/ayon-shotgrid/issues/22#issuecomment-1787618274_

--------

> At this stage, most of the parameters aren't being synchronized, so it's "expected behaviour", wanted to get into a poitn where people can tell me which are must haves, and then maybe put others behind settings.

Gotcha, that's all good it's better for me to know what's meant to be syncronised so I can manually import data and assume it won't be overwritten.
In general, I'm happy to work with you on what the standard 'set' of Seq/Scn/Shot/Task/Version fields are in the VFX space.

That being said, just as you mentioned putting others behind settings, would it maybe be a good idea to just put all of it behind settings so the studio can custom map field to field? Assuming the data type is equal.
![image](https://github.com/ynput/ayon-shotgrid/assets/1258632/b9549750-fd7d-4c16-a36a-462b1c8eea86)
https://excalidraw.com/#room=f4296cdbc2d04f7c1b06,5-4T1vZhIYoF4k-IWau4BA

--------

**Comment by jakubjezek001** [comment]
This was solved within https://github.com/ynput/ayon-shotgrid/pull/72
