### ISSUE TITLE
Minor: Tab Load White Page Flash

### ISSUE THREAD

**Issue by matteoveglia** [ynput/ayon-shotgrid#56]
Reported by Fabia Serra on the Discord:
https://discord.com/channels/517362899170230292/890894521817260052/1176891667010297866

----

There appears to be a small issue where when clicking on ShotGrid Sync from another tab in AYON gives a quick flash of white background page colour before loading the addon ui.

https://github.com/ynput/ayon-shotgrid/assets/1258632/8ab41ebd-5d79-40a9-bbc5-caec16afab29

**Comment by jakubjezek001** [comment]
this might have been an issue on frontend of AYON server. @martastain or @Innders, was there any report on this? Was this already addressed?

**Comment by jakubjezek001** [comment]
Closing the issue since it is frontend related.
